sonar.projectKey=DENFR18_devops-factory_service-alpha
sonar.organization=denfr18
sonar.projectName=service-alpha

sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,**/__pycache__/**,*.pyc,.trivyignore

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
