apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-alpha-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: tenant-alpha-service
    app.kubernetes.io/part-of: tenants
    tenant: alpha
spec:
  project: tenant-alpha
  source:
    repoURL: https://github.com/DENFR18/devops-factory.git
    targetRevision: main
    path: charts/service-alpha
    helm:
      valueFiles:
        - ../../argocd/tenants/alpha/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
