apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-alpha
  namespace: argocd
  labels:
    app.kubernetes.io/name: tenant-alpha
    app.kubernetes.io/part-of: tenants
    tenant: alpha
spec:
  description: Tenant alpha applications
  sourceRepos:
    - https://github.com/DENFR18/devops-factory.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: tenant-alpha
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: Ingress
