image:
  repository: rg.fr-par.scw.cloud/devops-factory/service-alpha
  tag: "sha-005f724"
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: true
  host: alpha.devops-factory.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
