stages:
  - lint
  - test
  - build
  - push_image
  - security_scan
  - infra_plan
  - infra_apply
  - deploy

variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  ACR_IMAGE: "acrdevopsfactorydev.azurecr.io/devops-factory:$CI_COMMIT_SHORT_SHA"

#lint
lint:
  stage: lint
  image: node:20
  script:
    - npm install
    - npm run lint

# test unitaires
unit_tests:
  stage: test
  image: node:20
  script:
    - npm install
    - npm run test

# build Docker
build_docker:
  stage: build
  image: docker:24
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .
    - docker images

# Scan sécurité avec Trivy
security_scan:
  stage: security_scan
  image: alpine:latest
  script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    - ./bin/trivy image --username $ACR_USERNAME --password $ACR_PASSWORD --exit-code 0 --severity HIGH,CRITICAL $ACR_IMAGE

# Push Docker vers ACR:
push_image:
  stage: push_image
  image: docker:24
  services:
    - docker:dind
  script:
    - echo $ACR_PASSWORD | docker login acrdevopsfactorydev.azurecr.io -u $ACR_USERNAME --password-stdin
    - docker build -t $ACR_IMAGE .
    - docker push $ACR_IMAGE
  
# Terraform plan (automatique sur chaque push)
terraform_plan:
  stage: infra_plan
  image:
    name: hashicorp/terraform:1.7
    entrypoint: [""]
  script:
    - cd infra
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - infra/tfplan
      - infra/.terraform.lock.hcl
    expire_in: 1 day
  rules:
    - when: never

# Terraform apply (manuel)
terraform_apply:
  stage: infra_apply
  when: manual
  image:
    name: hashicorp/terraform:1.7
    entrypoint: [""]
  script:
    - cd infra
    - terraform init
    - terraform apply -auto-approve
  dependencies:
    - terraform_plan
  rules:
    - when: never

# Déploiement HELM Kubernetes
deploy:
  stage: deploy
  when: manual
  image:
    name: alpine/helm:3.12.0
    entrypoint: [""]
  script:
    - printf '%s' "$KUBE_CONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=$(pwd)/kubeconfig
    - helm upgrade --install my-app ./helm-chart --namespace dev --create-namespace --values ./helm-chart/values-dev.yaml --set image.tag=$CI_COMMIT_SHORT_SHA
  environment:
    name: dev
    url: https://dev.my-app.com