sonar.projectKey=DENFR18_devops-factory
sonar.organization=denfr18

sonar.sources=app.js,frontend
sonar.exclusions=infra/**,docs/**,k8s/**,.github/**,.gitlab/**,apps/**,helm-chart/**,node_modules/**,manifests/**,charts/**,argocd/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
