image:
  repository: rg.fr-par.scw.cloud/devops-factory-dev/node-api
  tag: "sha-b1e5544"
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: true
  host: beta.devops-factory.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  PORT: "3000"
