sonar.projectKey=DENFR18_devops-factory_react
sonar.organization=denfr18
sonar.projectName=react

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx
sonar.exclusions=node_modules/**,dist/**,.trivyignore
sonar.javascript.lcov.reportPaths=lcov.info
