sonar.projectKey=DENFR18_devops-factory_node-api
sonar.organization=denfr18
sonar.projectName=node-api

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js
sonar.exclusions=node_modules/**,.trivyignore
