apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    app.kubernetes.io/part-of: platform
spec:
  project: default
  source:
    repoURL: https://github.com/DENFR18/devops-factory.git
    targetRevision: HEAD
    path: argocd/platform/cert-manager-issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
