apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cloud-forge
    tenant: react
spec:
  project: default
  source:
    repoURL: https://github.com/DENFR18/devops-factory.git
    targetRevision: HEAD
    path: charts/react
  destination:
    server: https://kubernetes.default.svc
    namespace: react
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
