apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-wordpress
  namespace: argocd
  labels:
    app.kubernetes.io/name: stack-wordpress
    app.kubernetes.io/part-of: app-catalog
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 30.0.13
    helm:
      releaseName: wordpress
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: false
        persistence:
          enabled: false
        resourcesPreset: nano
        mariadb:
          enabled: true
          primary:
            persistence:
              enabled: false
            resourcesPreset: nano
  destination:
    server: https://kubernetes.default.svc
    namespace: stack-wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-mysql
  namespace: argocd
  labels:
    app.kubernetes.io/name: stack-mysql
    app.kubernetes.io/part-of: app-catalog
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: 14.0.3
    helm:
      releaseName: mysql
      values: |
        architecture: standalone
        auth:
          database: devops_factory
        primary:
          persistence:
            enabled: false
          resourcesPreset: nano
  destination:
    server: https://kubernetes.default.svc
    namespace: stack-wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
