apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-vault
  namespace: argocd
  labels:
    app.kubernetes.io/name: stack-vault
    app.kubernetes.io/part-of: security
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      releaseName: vault
      values: |
        server:
          dev:
            enabled: true
          dataStorage:
            enabled: false
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 250m
        ui:
          enabled: true
          serviceType: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
