apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-mattermost
  namespace: argocd
  labels:
    app.kubernetes.io/name: stack-mattermost
    app.kubernetes.io/part-of: app-catalog
spec:
  project: default
  source:
    repoURL: https://helm.mattermost.com
    chart: mattermost
    targetRevision: 2.7.0
    helm:
      releaseName: mattermost
      values: |
        mattermostApp:
          ingress:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: stack-mattermost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
