apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-gamma
  namespace: argocd
  labels:
    app.kubernetes.io/name: tenant-gamma
    app.kubernetes.io/part-of: tenants
    tenant: gamma
spec:
  project: default
  source:
    repoURL: https://github.com/DENFR18/devops-factory.git
    targetRevision: main
    path: argocd/tenants/gamma
    directory:
      exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
