---
# Image à builder et pusher dans ACR par le 3ème coéquipier
# Remplacer <ACR_URL> par : acrdevopsfactorydev.azurecr.io
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: stack-node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: acrdevopsfactorydev.azurecr.io/node-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-api
  namespace: stack-node-api
spec:
  selector:
    app: node-api
  ports:
    - port: 3000
      targetPort: 3000
